name: 05 - 1 - Event Filters and Activity Types

on: 
  pull_request:
    types: [opened, synchronize]
    branches: [main]  

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow runs only for pull request events of type 'opened' and 'synchronize' on the 'main' branch."