name: 07 - Using Expressions

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      debug:
        description: Debug mode
        type: boolean
        default: false

jobs:
  echo: #fixed issue at line 17
    runs-on: ubuntu-latest
    steps:
      - name: [debug] Print start up data
        if: ${{ inputs.debug }}
        run: |
        
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Commit SHA: ${{ github.sha }}"
